name: Metrics
on:
    schedule:
        - cron: '30 1 * * *'
    workflow_dispatch:
    push:
        branches:
            - metrics-action

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                token: ${{ secrets.METRICS_TOKEN }}
                output_action: commit
                committer_branch: main
                committer_message: update github-metrics.svg
                output_condition: data-changed
                plugin_isocalendar: yes
                plugin_isocalendar_duration: full-year
                plugin_languages: yes
                template: repository
                config_padding: 5%
